export const COURSES = [
  {
    "id": "u1",
    "courses": [
      "Learn Angular 5 from Scratch",
      "3 Minute French - Course 3 | Language lessons for beginners",
      "Magento 2.4 für Linux-Admins – Perfekte Server-Installation",
      "Flutter & Dart - The Complete Guide [2025 Edition]",
      "React - The Complete Guide 2025 (incl. Next.js, Redux)",
      "The Complete Flutter Development Bootcamp with Dart",
      "JavaScript Unit Testing - The Practical Guide",
      "3 Minute French - Course 4 | Language lessons for beginners",
      "Tailwind CSS Einführung - eine neue Art CSS zu denken!",
      "Master 320 Common English Phrases",
      "Advanced Ionic & Angular: 10 Techniques in Web Development",
      "Progressive Web Apps (PWA) - The Complete Guide",
      "React vs Angular vs Vue.js by Example",
      "React Fundamentals",
      "React basic in just 1 hour [2022]",
      "3 Minute French - Course 5 | Language lessons for beginners",
      "3 Minute French - Course 2 | Language lessons for beginners",
      "3 Minute Italian - Course 3 | Language lessons for beginners",
      "3 Minute Italian - Course 2 | Language lessons for beginners",
      "3 Minute Spanish - Course 2 | Language lessons for beginners",
      "3 Minute Spanish - Course 1 | Language lessons for beginners",
      "The Complete JavaScript Course 2025: From Zero to Expert!",
      "Build a simple chat system in JavaScript",
      "Essentials in JavaScript ES6 - A Fun and Clear Introduction",
      "ES6 Javascript: The Complete Developer's Guide",
      "JavaScript Objects - Explore and learn about Objects",
      "Advanced and Object Oriented JavaScript and ES6",
      "French for Middle Schoolers - Part 2",
      "English Speaking Patterns Mastery: Upgrade your English",
      "Accelerated ES6 JavaScript Training",
      "JavaScript - The Complete Guide 2025 (Beginner + Advanced)",
      "Advanced Javascript",
      "Javascript Debugging Crash Course",
      "Learning Path: Magento: Master and Test Magento 2 with Ease",
      "Magento Course - Complete Magento certified developer exam",
      "Become a Magento Developer - Front End (Subtitled EN)",
      "3 Minute French - Course 1 | Language lessons for beginners",
      "Learn Jira with real-world examples 2024 (+Confluence bonus)",
      "Pediatric Advanced Life Support (PALS)",
      "Learn guitar the Right way! Beginner to intermediate guitar",
      "Guitar: Learn To Play 10 Guitar Songs Using Just 3 Chords",
      "Shopware Developer Training Advanced",
      "Alpine JS Vs. 3 For Beginners. Learn the new alpine.js v3!",
      "Shopware Developer Training Advanced - English",
      "Krav Maga - Hocheffiziente Selbstverteidigung",
      "Tutorial: Grundlagen von GitHub - Fork, Pull Request und Co.",
      "English Language Course - Advanced Dictations",
      "Vue - The Complete Guide (incl. Router & Composition",
      "The Ultimate Vue 2 Crash Course - Learn by Example",
      "Full-Stack Vue with GraphQL - The Ultimate Guide",
      "Laravel API Development & Vue JS SPA from Scratch",
      "EMMET Faster HTML & CSS workflow - Best Tool For Developers",
      "PHP-Bootcamp: Vom Anfänger zum PHP-Entwickler",
      "Learn Symfony 3 framework by practical examples",
      "PHP Data Objects (PDO)",
      "PHP: The Complete PHP MVC Course",
      "Advanced CSS and Sass: Flexbox, Grid, Animations and More!",
      "Shopware Template Training - Basic",
      "Shopware Template Training - Advanced",
      "LEARNING PATH: jQuery: Master Web Development with jQuery 3",
      "Build Responsive Website Using HTML5, CSS3, JS And Bootstrap",
      "Modernes JavaScript (ES6): jQuery, node.js, und viel Praxis!",
      "Object-oriented Programming in JavaScript",
      "Extensionentwicklung mit Typo3 CMS V8.7.x",
      "French for Middle Schoolers",
      "Learn to speak : daily conversation in french",
      "Improve your French Now",
      "Objektorientierte Entwicklung mit PHP 7",
      "The Complete Google Forms Course - Sending & Analyzing Forms",
      "Docker & Kubernetes: The Practical Guide [2025 Edition]",
      "React & TypeScript - The Practical Guide",
      "Introduction to Swiss German",
      "Quickstart AngularJS 1.0 [First Version Of Angular]",
      "AngularJS 1.0 Masterclass - Deep Dive & Understand AngularJS",
      "Shopware Developer Training Basic",
      "Praktische Tipps für die Gehaltserhöhung",
      "Ultimate AWS Certified Developer Associate 2025 DVA-C02",
      "The AWS Course - Updated 2023",
      "French Foundation Course with Pronunciation Techniques",
      "French for Middle Schoolers - Part 3",
      "American English for French Speakers",
      "The Complete PHP Bootcamp Course With Video Sharing Project",
      "Secure Your VueJs Applications With Auth0"
    ]
  },
  {
    "id": "u2",
    "courses": [
      "Build 7 Real World Applications with Vue.js",
      "LEARNING PATH: jQuery: Master Web Development",
    ]
  },
  {
    "id": "u7",
    "courses": [
      "Angular - The Complete Guide (2025 Edition)",
      "RxJS 7 and Observables: Introduction",
      "NodeJS - The Complete Guide (MVC, REST APIs, GraphQL,",
    ]
  },
];
